version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: resume-optimizer-mongodb
    restart: unless-stopped
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=resume_optimizer
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: resume-optimizer-backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=resume_optimizer
    networks:
      - app-network
    volumes:
      - ./backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: resume-optimizer-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge